name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /var/www/MonitoringSD
            git config --global --add safe.directory /var/www/MonitoringSD
            git fetch origin
            git reset --hard origin/main

            # Optional: jika menggunakan submodules
            # git submodule update --init --recursive

            # Install dependencies
            composer install --no-dev --optimize-autoloader

            # Laravel deploy steps
            php artisan down || true

            php artisan clear-compiled
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            php artisan up

            # Pastikan permission OK
            chown -R www-data:www-data .
